#!/bin/sh
#
# Copyright 2017 Gaël PORTAY <gael.portay@savoirfairelinux.com>
#
# Licensed under the MIT license.
#

set -e

# Not called by hotplug
if [ -z "$DEVPATH" ]; then
	# Root does not need to su
	if [ "$(id -u)" -eq 0 ]; then
		su_root="sh"
	fi

	# Trigger uevent on card0
	exec ${su_root:-su root} -c "echo \"${1:-change}\" >/sys/class/drm/card0/uevent"
fi

# Called by hotplug
# Be safe, drop privileges
su - nobody -s "${SHELL:-/bin/sh}"

# Create a temporary directory to record status of each connectors
tmpdir="/tmp/${0##*/}"
mkdir -p "$tmpdir"

# Check status of all connectors
card="${DEVPATH##*/}"
for dev in "/sys$DEVPATH/$card-"*; do
	name="${dev##*/$card-}"
	action="change"
	status="$(cat "$dev/status")"

	# This case never happens is a usual situation. It is triggered when the
	# script is called directly with remove as argument
	# shellcheck disable=SC2153 disable=SC2115
	if [ "$ACTION" = "remove" ]; then
		rm -rf "$tmpdir/$name"
		echo "remove" >"$dev/uevent"
		continue
	# New connector, set action to add
	elif [ ! -d "$tmpdir/$name" ]; then
		action="add"
		mkdir -p "$tmpdir/$name"
		cp "$dev/status" "$tmpdir/$name"
	# Status unchanged, keep going
	elif [ "$(cat "$tmpdir/$name/status")" = "$status" ]; then
		continue
	fi

	# Save status
	cp "$dev/status" "$tmpdir/$name"

	# Trigger uevent
	echo "$action" >"$dev/uevent"
done
